version: "3.8"

services:
  web:
    build: .
    container_name: admin-front
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ../TFG-BACKEND
      dockerfile: Dockerfile
    container_name: admin-back
    ports:
      - "5050:5050"
    env_file:
      - ../TFG-BACKEND/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
