version: "3.8"

services:
  mongo:
    container_name: mongo_db
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    image: admin-backend:latest
    container_name: admin-back
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    env_file:
      - ./TFG-BACKEND/.env
    networks:
      - app-network

  frontend:
    image: admin-frontend:latest
    container_name: admin-front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5050

networks:
  app-network:
    driver: bridge
