version: "3.8"

services:
  mongo:
    container_name: mongo_db
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./TFG-BACKEND
      dockerfile: Dockerfile
    container_name: admin-back
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    env_file:
      - ./TFG-BACKEND/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./TFG-FRONTEND
      dockerfile: Dockerfile
    container_name: admin-front
    ports:
      - "5173:5173"
    volumes:
      - ./TFG-FRONTEND:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:5050
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
