version: "3.8"

services:
  tfg-frontend-web:
    # ...existing code...

  tfg-frontend-backend:
    container_name: tfg-backend
    # ...existing code...

  mongo:
    # ...existing code...

networks:
  app-network:
    driver: bridge
