services:
  mongo:
    container_name: mongo_db
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    #volumes:
    #  - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-back
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    env_file:
      - .env
    #volumes:
    #  - .:/usr/src/app

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seed
    command: npm run seed
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: "no"

volumes:
  mongodb_data:
